# Generated by Django 3.2.6 on 2021-10-15 23:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_descritpion_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
